version: '3.8'

services:
  website-front:
    image: nginx:latest
    container_name: website-front
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/website/front/html:/usr/share/nginx/html
      - /data/website/front/nginx-https.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - web

networks:
  web:
    driver: bridge